# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspring', '0003_auto_20190327_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspring',
            name='comment',
            field=models.TextField(),
        ),
    ]
