# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspring', '0004_auto_20190327_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspring',
            name='state',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
