# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspring', '0005_hotspring_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspring',
            old_name='users',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='hotspring',
            name='message',
        ),
    ]
